language: python
python:
  - "2.7.12"
env:
  - DJANGO=1.9.7
install:
  - pip install -q Django==$DJANGO
  - pip install pep8
  - pip install codecov
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: change
script:
  - python manage.py runserver &
